### ISSUE TITLE
test on ARM RaspberryPi

### ISSUE THREAD

**Issue by yolateng0** [LiveChief/wireguard-install#27]
test no effect
"wireguard-server.sh: line 266: wg: command not found
wireguard-server.sh: line 267: wg: command not found
wireguard-server.sh: line 297: qrencode: command not found

**Comment by LiveChief** [comment]
this is for ubuntu / debian ///\\\ isn't made for Raspberry PI 

will try and update the script soon.

**Comment by yolateng0** [comment]
it s Raspbian
i ll try it

**Comment by LiveChief** [comment]
ill do this in a couple of days, if u manage to make the script work before than please make a pull for raspberrypi (on the script) and you'll be helping the community.


also please help with this if u can 
https://github.com/LiveChief/wireguard-install/blob/master/wireguard-server.sh#L136

**Comment by LiveChief** [comment]
tried it right now on raspberry pi 3 and it worked fine.

**Comment by Keplo** [comment]
Hay,
Thanks for the update. I tried the script on an ARM Board Olimux Lime 2 with debian/yunohost.

Tell me a name for the client config file. Use one word only, no special characters.
Client name: Funnel
▀██▀  █▀█ █▄█▄█▄ ▄████
████▄▄▄▄▄▄▄█▄▄███▄▄▄██▄▄▄███▄▄▄█▄█▄▄██████▄█▄███▄█▄▄▄▄█▄█████
█████████████████████████████████████████████████████████████
█████████████████████████████████████████████████████████████
Client added, new configuration file --> /root/Funnel-wg0.conf                                                                                                
root@mydomain:~# wg                                                                                                                                            
root@mydomain:~# ip link add dev wg0 type wireguard                                                                                                            
RTNETLINK answers: Operation not supported                                                                                                                    
root@mydomain:~# systemctl start wg-quick@wg0.service                                                                                                          
Job for wg-quick@wg0.service failed because the control process exited with error code.                                                                       
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.                                                                                 
root@mydomain:~# systemctl status wg-quick@wg0.service                                                                                                         
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/lib/systemd/system/wg-quick@.service; disabled; vendor preset: enabled)                                                                   
   Active: failed (Result: exit-code) since Mon 2019-05-13 14:42:16 UTC; 16s ago
     Docs: man:wg-quick(8)                                                                                                                                    
           man:wg(8)                                                                                                                                          
           https://www.wireguard.com/                                                                                                                         
           https://www.wireguard.com/quickstart/                                                                                                              
           https://git.zx2c4.com/WireGuard/about/src/tools/man/wg-quick.8                                                                                     
           https://git.zx2c4.com/WireGuard/about/src/tools/man/wg.8                                                                                           
  Process: 10940 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=1/FAILURE)
 Main PID: 10940 (code=exited, status=1/FAILURE)                                                                                                              
                                                                                                                                                              
May 13 14:42:16 whatever.fr systemd[1]: Starting WireGuard via wg-quick(8) for wg0...                                                                     
May 13 14:42:16 whatever.fr wg-quick[10940]: [#] ip link add wg0 type wireguard                                                                           
May 13 14:42:16 whatever.fr wg-quick[10940]: RTNETLINK answers: Operation not supported                                                                   
May 13 14:42:16 whatever.fr wg-quick[10940]: Unable to access interface: Protocol not supported                                                           
May 13 14:42:16 whatever.fr wg-quick[10940]: [#] ip link delete dev wg0                                                                                   
May 13 14:42:16 whatever.fr wg-quick[10940]: Cannot find device "wg0"                                                                                     
May 13 14:42:16 whatever.fr systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=1/FAILURE                                          
May 13 14:42:16 whatever.fr systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.
May 13 14:42:16 whatever.fr systemd[1]: wg-quick@wg0.service: Unit entered failed state.                                                                  
May 13 14:42:16 whatever.fr systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.

**Comment by Keplo** [comment]
For your information :
Root: uname -r
4.14.84-sunxi

**Comment by LiveChief** [comment]
@Keplo @yolateng0

Test it now, it worked for my raspberry pi.
